### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by tcamechis-cni** [atomisthq/jibbit#11]
Is there a way to have multiple targets?  Say one for when running locally and another that pushes to remote registry.

**Comment by tcamechis-cni** [comment]
I think i figured out a simple way to do this by just creating a separate edn file and directing the cli to it.

**Comment by slimslenderslacks** [comment]
@tcamechis-cni - ya, having a second file should work, and I think that's the right way to do it for now.  I keep wondering whether the config maps for jibbit should be turned into deps.edn aliases?  For now, I think what you're doing with separate files is probably the best way to do it.  I'll make a note in the README.md.
