### ISSUE TITLE
jibbit seem to ignore custom paths in deps.edn - how can I provide my own JAR?

### ISSUE THREAD

**Issue by esuomi** [atomisthq/jibbit#12]
Hi!

My project uses non-default source and resource paths (_created with command `mkdir -p {dev,main,test}/{src,resources}`_) and it seems that when following instructions naïvely from the project README, the resulting layer has `main/src` and `main/resources` prefixes for the relevant files, instead of correct roots, which of course leads to non-existent main ns being loaded, a stacktrace and exit.

Can I provide my own JAR instead, and if so, what should the build script for it be? Eg. tools.build

**Comment by slimslenderslacks** [comment]
Hi @esuomi - let me check.  I had a test case for this so let me check quickly with a `main/src` and `main/resources`.

**Comment by slimslenderslacks** [comment]
@esuomi sorry this is taking so long - I ended up being away for a week.  By default, the application layer should have `/home/app/main/src` and `/home/app/main/resources` and those entries should be listed on the classpath for the entrypoint (`/home/app` is the WORKDIR in the container so the entries in the classpath will be `main/src` and `main/resources`).  There's an `:aot` option to do compile the jar beforehand but really, this default configuration should have worked here so I'm still trying to reproduce the problem on my side.

**Comment by esuomi** [comment]
@slimslenderslacks 

> sorry this is taking so long - I ended up being away for a week.

Eh, no sweat - life happens :)

> I'm still trying to reproduce the problem on my side

I'll try to squeeze some time from myself to create a shareable reproduction of this issue. Might take a few days, tomorrow's [Midsummer Eve](https://en.wikipedia.org/wiki/Midsummer#Finland) which is always kind of a hassle at work since everyone's frantically clearing their desks for summer vacations... :)

**Comment by slimslenderslacks** [comment]
Thanks!  I'd like to also verify that you're running `clj -Tjib` in the same `pwd` as your deps.edn.  Happy midsummer!

**Comment by slimslenderslacks** [comment]
@esuomi wondering if you've had another chance to look at this.  I've got some local test cases where the non-standard src dirs are being packaged as I had anticipated.  So I haven't been able to reproduce this accurately yet.

**Comment by esuomi** [comment]
@slimslenderslacks Alright, so I _finally_ had time to make a repro out of this, and turns out it's kinda simple - all configuration examples in README look something like this:
```edn
{:main "hello.world"
 ...}
```

The issue is with quotes; removing them makes everything work as expected. With quotes hijinks ensue and results look like this:
```edn
; jib.edn
{:main "hello"
 :target-image {:image-name "my/hello"
                :type :docker}}
```
```shell
➜  jibbit-custom-dirs-repro clj -Tjib build
... run jib
fatal: No remote configured to list refs from.
could not discover git remote
Registry image: gcr.io/distroless/java
fatal: not a git repository (or any of the parent directories): .git
Local docker: my/hello
jib:WARN      Base image 'gcr.io/distroless/java' does not use a specific image digest - build may not be reproducible
jib:PROGRESS  Getting manifest for base image gcr.io/distroless/java...
jib:PROGRESS  Building clojure application layer layer...
jib:PROGRESS  Building dependencies layer layer...
jib:LIFECYCLE Using base image with digest: sha256:629d4fdc17eec821242d45497abcb88cc0442c47fd5748baa79d88dde7da3e2d
jib:LIFECYCLE
jib:LIFECYCLE Container entrypoint set to [java, -Dclojure.main.report=stderr, -Dfile.encoding=UTF-8, -cp, main/src:main/resources:lib/camel-snake-kebab__camel-snake-kebab_camel-snake-kebab-0.4.3.jar:lib/org.clojure__clojure_clojure-1.10.3.jar:lib/org.clojure__core.specs.alpha_core.specs.alpha-0.2.56.jar:l<... classpath truncated ...>, clojure.main, -m, "hello"]
jib:PROGRESS  Loading to Docker daemon...

➜  jibbit-custom-dirs-repro docker run my/hello
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{:clojure.main/message
 "Execution error (FileNotFoundException) at clojure.main/main (main.java:40).\nCould not locate \"hello\"__init.class, \"hello\".clj or \"hello\".cljc on classpath.\n",
 :clojure.main/triage
 {:clojure.error/class java.io.FileNotFoundException,
  :clojure.error/line 40,
  :clojure.error/cause
  "Could not locate \"hello\"__init.class, \"hello\".clj or \"hello\".cljc on classpath.",
  :clojure.error/symbol clojure.main/main,
  :clojure.error/source "main.java",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type java.io.FileNotFoundException,
    :message
    "Could not locate \"hello\"__init.class, \"hello\".clj or \"hello\".cljc on classpath.",
    :at [clojure.lang.RT load "RT.java" 462]}],
  :trace
  [[clojure.lang.RT load "RT.java" 462]
   [clojure.lang.RT load "RT.java" 424]
   [clojure.core$load$fn__6856 invoke "core.clj" 6115]
   [clojure.core$load invokeStatic "core.clj" 6114]
   [clojure.core$load doInvoke "core.clj" 6098]
   [clojure.lang.RestFn invoke "RestFn.java" 408]
   [clojure.core$load_one invokeStatic "core.clj" 5897]
   [clojure.core$load_one invoke "core.clj" 5892]
   [clojure.core$load_lib$fn__6796 invoke "core.clj" 5937]
   [clojure.core$load_lib invokeStatic "core.clj" 5936]
   [clojure.core$load_lib doInvoke "core.clj" 5917]
   [clojure.lang.RestFn applyTo "RestFn.java" 142]
   [clojure.core$apply invokeStatic "core.clj" 669]
   [clojure.core$load_libs invokeStatic "core.clj" 5974]
   [clojure.core$load_libs doInvoke "core.clj" 5958]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.core$apply invokeStatic "core.clj" 669]
   [clojure.core$require invokeStatic "core.clj" 5996]
   [clojure.main$main_opt invokeStatic "main.clj" 514]
   [clojure.main$main_opt invoke "main.clj" 510]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause
  "Could not locate \"hello\"__init.class, \"hello\".clj or \"hello\".cljc on classpath."}}

Execution error (FileNotFoundException) at clojure.main/main (main.java:40).
Could not locate "hello"__init.class, "hello".clj or "hello".cljc on classpath.
```

Some environment details in case that matters:
```shell
➜  jibbit-custom-dirs-repro uname -a
Darwin MACGH3Z1Q05P 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:36:53 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T8101 arm64
➜  jibbit-custom-dirs-repro java --version
openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode)
➜  jibbit-custom-dirs-repro docker --version
Docker version 20.10.13, build a224086
```

**Comment by slimslenderslacks** [comment]
@esuomi thanks!  You're absolutely right.  There's an ambiguity here between string and symbol.  I think it's probably more intuitive to go through and make sure the docs all references `:main` `symbol`s.  I think it's probably even a good idea to fail with a good message if a the value of `:main` is anything except a symbol.  I think we made that change a while back and didn't update the README.  

I'll update the README to make this more clear.

**Comment by tcamechis-cni** [comment]
We are having a similar issue.  In my case we are working inside a monorepo using clojure polylith.  I think the issue is the folder with the build does not have any src but is all referenced as deps "local/root".

**Comment by slimslenderslacks** [comment]
@tcamechis-cni I had tested with polylith on one project (https://github.com/atomisthq/jibbit/wiki/polylith-example) and I was using this to verify that this project https://github.com/slimslenderslacks/clojure-polylith-realworld-example-app/blob/master/projects/realworld-backend-jib/deps.edn.  

I don't have an automated test case for this one though.  I wonder if it's not working anymore.  The final basis that deps creates for a project like this will have lots of source folders to copy into the layer and add to the classpath.  But this project represent the style you're using right?

**Comment by tcamechis-cni** [comment]
Yep

**Comment by slimslenderslacks** [comment]
@tcamechis-cni - I've been testing this with https://github.com/slimslenderslacks/clojure-polylith-realworld-example-app/blob/master/projects/realworld-backend-jib/deps.edn

I run `clj -Tjib build` in that directory and then I'm using `docker inspect` on the resulting image to look at the `Config.Entrypoint`, which should have a `-cp` entry with a whole bunch source folders (named after your lib entries).  I'm using the `dive` tool to verify that this code is all copied into the `/home/app` folder.  So this test is working.

Does your project happen to be in a public repo that I could clone and build.  All of your local/roots should be copied into the /home/app folder of the final layer, and there should be classpath entries too.  Maybe it's something else?

**Comment by esuomi** [comment]
I'm fine with these changes now and I'm considering the issue resolved - do you want me to close the issue or would you @slimslenderslacks want to have the honor? :)

**Comment by slimslenderslacks** [comment]
@esuomi thanks!!!

**Comment by slimslenderslacks** [comment]
@tcamechis-cni btw, if you've got other some related issue around polylith layouts, let's start another issue - I havne't reproduced it yet but I'd up for it for sure.
