### ISSUE TITLE
main-opts and jvm-opts are being extracted from basis incorrectly

### ISSUE THREAD

**Issue by puredanger** [atomisthq/jibbit#19]
In doing some work on the basis recently, I discovered that due to some sloppy coding on my part, the basis contained more data than it should have in the `:resolve-args` and `:classpath-args` keys.

In particular these code locations are pulling either `:jvm-opts` or `:main-opts` from the `:classpath-args` map. Neither of these are classpath args and were never expected to be data that should be there:

* https://github.com/atomisthq/jibbit/blob/main/src/jibbit/core.clj#L138
* https://github.com/atomisthq/jibbit/blob/main/src/jibbit/core.clj#L143
* https://github.com/atomisthq/jibbit/blob/main/src/jibbit/core.clj#L310

So, you should not be doing that. However, I do think it is reasonable to want those merged jvm-opts and main-opts and the basis now contains an official place to get that info in a new basis key `:argmap`.

To fix, update to at least tools.build 0.9.4, and replace `:classpath-args` with `:argmap`. The `:classpath-args` are deprecated and will be removed in the near future.

**Comment by slimslenderslacks** [comment]
@puredanger Thanks for this.  I'll switch this over to use the :argmap and update to 0.9.4.
