### ISSUE TITLE
Repository is missing main branch

### ISSUE THREAD

**Issue by loganlinn** [atomisthq/jibbit#21]
Github showing this repository as not having any branches. Is this intentional?

```sh-session
$ git ls-remote --heads https://github.com/atomisthq/jibbit.git
```

Last known commit appears to be from #20  (b05238295e74a1688797a53c73d5afb83042c433)

**Comment by slimslenderslacks** [comment]
I still don't know what happened to the main branch ref.  I can't find any audit of how it was removed or why.

**Comment by slimslenderslacks** [comment]
I think I've restored the main branch ref to where it should be and I've added branch protection to the repo.  I wish I could figure out how this branch ref got deleted though.  Sorry about this.

**Comment by loganlinn** [comment]
Looks good, thanks! No worries, I've been there ;) And yeah, I think only Github Enterprise provides visibility for this sort of thing, for whatever reason.
