### ISSUE TITLE
Support local/root / polylith projects

### ISSUE THREAD

**Issue by olymk2** [atomisthq/jibbit#5]
Discussed on slack with @slimslenderslacks but thought I would raise an issue so its not forgotten.

If you use a code base in the polylith format the generated container is incomplete.

There is an example project here 
https://github.com/furkan3ayraktar/clojure-polylith-realworld-example-app/tree/master/projects/realworld-backend

The cause of the issues is that polylith uses local/root and often relative paths so the components do not get picked up and included in the final build.

**Comment by slimslenderslacks** [comment]
Great, thanks @olymk2!  I've started working on this in a branch.  You can currently try it with

```
:jib     {:deps {io.github.atomisthq/jibbit {:git/url "https://github.com/atomisthq/jibbit.git"
                                             :git/sha "41d71f062acabc4e8469adb94e0ccfb51ab19541"}}
          :ns-default jibbit.core}
```

It's mostly about copying in the the polylith local/roots in a way that preserves the classpath.  I also added a function to fully detail how code is being copied into the layers and how the entrypoint is created.  You can debug this with:

```
clj -T:jib layers
```

**Comment by slimslenderslacks** [comment]
One note about https://github.com/furkan3ayraktar/clojure-polylith-realworld-example-app/tree/master/projects/realworld-backend

The `:ring` alias uses an extra library called furkan3ayraktar/polylith-clj-deps-ring to start the project in a repl.  This library uses a deps.edn to create a classloader context that can run the ring server.  This won't work after re-packaging it into a docker image unless the relative package structure is preserved exactly.  However, there's also a `clojure.realworld.rest-api.main` which is a good entrypoint.  I created a second project named `realworld-backend-jib` and added these two files:

jib.edn

```
{:aliases [:ring]
 :base-image {:image-name "openjdk:11-slim-buster"
              :type :registry}
 :target-image {:type :docker
                :image-name "polylith"}}
```

and deps.edn

```
{:mvn/repos {"central" {:url "https://repo1.maven.org/maven2/"}
             "clojars" {:url "https://clojars.org/repo"}}

 :deps      {poly/article  {:local/root "../../components/article"}
             poly/comment  {:local/root "../../components/comment"}
             poly/database {:local/root "../../components/database"}
             poly/env      {:local/root "../../components/env"}
             poly/log      {:local/root "../../components/log"}
             poly/profile  {:local/root "../../components/profile"}
             poly/spec     {:local/root "../../components/spec"}
             poly/tag      {:local/root "../../components/tag"}
             poly/user     {:local/root "../../components/user"}
             poly/rest-api {:local/root "../../bases/rest-api"}

             org.clojure/clojure {:mvn/version "1.10.3"}}

 :aliases   {:jib     {:deps {io.github.atomisthq/jibbit
                              {:local/root "/Users/slim/atmhq/jibbit"}
                              #_{:git/url "https://github.com/atomisthq/jibbit.git"
                                 :git/sha "41d71f062acabc4e8469adb94e0ccfb51ab19541"}}
                       :ns-default jibbit.core}

             :ring {:main-opts  ["-m" "clojure.realworld.rest-api.main"]}}}
```

If we build this `clj -T:jib build` then I can run it with `docker run --rm polylith`

I think this at least has all of the local-roots in the classpath.  I haven't tried with aot yet.

**Comment by slimslenderslacks** [comment]
@olymk2 - this branch is ready for you to try with your polylith project.

**Comment by olymk2** [comment]
I had a quick play using the images from the example it looks good, I want to try a few more things hopefully I can take a better look and do some testing with the bundled image soon and feed back. Thanks for spending to the time to support this most appreciated.

**Comment by slimslenderslacks** [comment]
Not being a user of polylith, we should probably merge this only when you think it's ready.  I have started using this branch for all of my non-polylith projects so I think it's going to be fine to merge when we're ready.

**Comment by olymk2** [comment]
So the image is being built but trying to run the container locally I get this error, not sure if its a me issue though, this is using the debian buster image from your example.

`
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: bpf_prog_query(BPF_CGROUP_DEVICE) failed: invalid argument: unknown.
`

Looking at the image in dive I can see all the files look like they have been copied under /home/app/

**Comment by olymk2** [comment]
Seem this is a me issue, hello world no longer works, looks like I gt a new docker version so likely related to that so will need to solve that then get back to you.

**Comment by slimslenderslacks** [comment]
@olymk2 did you figure this out?  This was from a `docker run ...`, right?  I haven't seen that error before so I was almost wondering whether you were using a different container runtime?

**Comment by olymk2** [comment]
Yeah I did, it was a me issue the laptop was on a lts kernel and the did not support a feature that newer docker required.
If your intrested, I switched to the latest and all was good.

https://discuss.getsol.us/d/8202-docker-not-working-related-to-recent-update 

I have since built and deploy to cloud run a container using jib, I need to change it back the the gcr jib container and see if that works, but for now at least it all seems to work great job and thanks for adding support :)

**Comment by slimslenderslacks** [comment]
Great, I think I'll merge this branch then.  I've not had any regressions using this branch.  And also, thank you for walking us through this.  These are good changes and I think we're closer to a packaging method that will cover a much broader range of what deps.edn can express.
